apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- install.yaml
- gateway_authorizationpolicy.yaml
- deny_all_authorizationpolicy.yaml
- gateway.yaml
- x-forwarded-host.yaml

namespace: istio-system

patchesStrategicMerge:
- patches/service.yaml
- patches/remove-pdb.yaml
- patches/istio-configmap-disable-tracing.yaml
images:
- name: docker.io/istio/pilot
  newName: harbor-repo.vmware.com/mlops/istio-pilot
  newTag: 1.9.6
- name: docker.io/istio/proxyv2
  newName: harbor-repo.vmware.com/mlops/istio-proxyv2
  newTag: 1.9.6
- name: gcr.io/arrikto/kubeflow/oidc-authservice
  newName: harbor-repo.vmware.com/mlops/oidc-authservice
  newTag: 28c59ef
