apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- ../../base
- service.yaml
- virtual-service.yaml

commonLabels:
  kustomize.component: profiles

patchesStrategicMerge:
- patches/kfam.yaml
- patches/remove-namespace.yaml

configurations:
- params.yaml

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: PROFILES_NAMESPACE
  objref:
    apiVersion: v1
    kind: Service
    name: profiles-kfam

images:
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newName: public.ecr.aws/j1r0q0g6/notebooks/access-management
  newTag: v1.4
- name: public.ecr.aws/j1r0q0g6/notebooks/access-management:v1.4
  newName: harbor-repo.vmware.com/mlops/access-management
  newTag: v1.4
- name: public.ecr.aws/j1r0q0g6/notebooks/profile-controller:v1.4
  newName: harbor-repo.vmware.com/mlops/profile-controller
  newTag: v1.4
