apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
namespace: kubeflow
patchesStrategicMerge:
- patches/remove-namespace.yaml
images:
- name: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
  newName: harbor-repo.vmware.com/mlops/kube-rbac-proxy
  newTag: v0.4.0
- name: public.ecr.aws/j1r0q0g6/notebooks/tensorboard-controller:v1.4
  newName: harbor-repo.vmware.com/mlops/tensorboard-controller
  newTag: v1.4
