apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- virtual-service.yaml
namespace: kubeflow
commonLabels:
  app: jupyter-web-app
  kustomize.component: jupyter-web-app
configurations:
- params.yaml
images:
- name: public.ecr.aws/j1r0q0g6/notebooks/jupyter-web-app:v1.4
  newName: harbor-repo.vmware.com/mlops/jupyter-web-app
  newTag: v1.4
