apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Manifests downloaded from:
# https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.yaml
resources:
- cert-manager.yaml

# XXX: Do NOT use the namespace transformer, as cert-manager defines resources
# in two namespaces, 'cert-manager' and 'kube-system'.
# For more information, see https://github.com/jetstack/cert-manager/issues/4102.

# Patch upstream manifests to explicitly disable 'preserveUnknownFields',
# otherwise upgrade with 'kubectl apply' fails.
patches:
- path: patches/crd-preserve-unknown-fields.yaml
  target:
    kind: CustomResourceDefinition
images:
- name: quay.io/jetstack/cert-manager-cainjector
  newName: harbor-repo.vmware.com/mlops/cert-manager-cainjector
  newTag: v1.3.1
- name: quay.io/jetstack/cert-manager-controller
  newName: harbor-repo.vmware.com/mlops/cert-manager-controller
  newTag: v1.3.1
- name: quay.io/jetstack/cert-manager-webhook
  newName: harbor-repo.vmware.com/mlops/cert-manager-webhook
  newTag: v1.3.1
