apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../katib-cert-manager
  # Kubeflow Katib components.
  - kubeflow-katib-roles.yaml
  - ui-virtual-service.yaml
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newName: harbor-repo.vmware.com/mlops/katib-controller
    newTag: v0.12.0
  - name: docker.io/kubeflowkatib/katib-db-manager
    newName: harbor-repo.vmware.com/mlops/katib-db-manager
    newTag: v0.12.0
  - name: docker.io/kubeflowkatib/katib-ui
    newName: harbor-repo.vmware.com/mlops/katib-ui
    newTag: v0.12.0
  - name: mysql
    newName: harbor-repo.vmware.com/mlops/mysql
    newTag: 8.0.26

patchesStrategicMerge:
  - patches/remove-namespace.yaml

vars:
  - fieldref:
      fieldPath: metadata.namespace
    name: KATIB_UI_NAMESPACE
    objref:
      apiVersion: apps/v1
      kind: Deployment
      name: katib-ui

configurations:
  - params.yaml
