apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: kubeflow

# Labels to add to all resources and selectors.
commonLabels:
  app: kfserving
  app.kubernetes.io/name: kfserving


patchesStrategicMerge:
- patches/statefulset.yaml
- patches/namespace.yaml
- patches/web-app-sidecar.yaml

patchesJson6902:
- path: patches/web-app-vsvc.yaml
  target:
    group: networking.istio.io
    kind: VirtualService
    name: kfserving-models-web-app
    namespace: kfserving-system
    version: v1beta1

generatorOptions:
  disableNameSuffixHash: true

# To make namespace for standalone installation kustomizable,
# variabalize ingress gateway, webhook service name and
# kfserving namespace in webhook configurations
configMapGenerator:
- behavior: replace
  envs:
  - params.env
  name: kfserving-config
- behavior: replace
  literals:
  - USERID_HEADER=kubeflow-userid
  name: kfserving-models-web-app-config

configurations:
- params.yaml
resources:
- ../../default
- cluster-role.yaml
- web-app-authorization-policy.yaml
images:
- name: docker.io/istio/proxyv2
  newName: harbor-repo.vmware.com/mlops/istio-proxyv2
  newTag: 1.9.6
- name: gcr.io/kubebuilder/kube-rbac-proxy
  newName: harbor-repo.vmware.com/mlops/kube-rbac-proxy
  newTag: v0.4.0
- name: kfserving/kfserving-controller
  newName: harbor-repo.vmware.com/mlops/kfserving-controller
  newTag: v0.6.1
- name: kfserving/models-web-app
  newName: harbor-repo.vmware.com/mlops/models-web-app
  newTag: v0.6.1
